apiVersion: v1
kind: Service
metadata:
  name: proto-web-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: proto-web
  ports:
  - name: web-port
    port: 8080
    nodePort: 30030
