apiVersion: v1
kind: Service
metadata:
  name: proto-api-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: proto-api
  ports:
  - name: app-port
    port: 4545
    nodePort: 30010
  - name: debug-port
    port: 9229
    nodePort: 30020
